[[pages]]
path = "pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/visualization.py"
name = "2D Visualization"
icon = "ğŸ“Š"

[[pages]]
path = "pages/classification.py"
name = "Classification Algorithms"
icon = "ğŸ¯"

[[pages]]
path = "pages/clustering.py"
name = "Clustering Algorithms"
icon = "ğŸ§©"

[[pages]]
path = "pages/info.py"
name = "Information"
icon = "â„¹ï¸"